[gauntlet]
name = 'File Search'
description = """
Search Files
"""

[[entrypoint]]
id = 'template-view'
name = 'Template view'
path = 'src/template-view.tsx'
type = 'view'
description = """
List View
"""

[permissions.filesystem]
read = [
  "{windows:user-home}"
  "{linux:user-home}"
  "{macos:user-home}"
]

